# Generated by Django 4.2.23 on 2025-09-08 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaBeneficiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AtencionIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_realizada', models.TextField()),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('EP', 'En Progreso'), ('RE', 'Resuelto'), ('CA', 'Cancelado')], default='PE', max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('area_beneficiaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attention.areabeneficiaria')),
                ('tipo_equipo_recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attention.tipoequiporecurso')),
                ('tipo_incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attention.tipoincidencia')),
            ],
        ),
    ]
