# Generated by Django 4.2.23 on 2025-08-11 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventoSoporteTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('descripcion_asistencia', models.TextField()),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='activitie.tipoactividad')),
            ],
        ),
    ]
