# Generated by Django 4.2.23 on 2025-09-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_beneficiario', models.CharField(max_length=150, verbose_name='Área / Beneficiario')),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=100, verbose_name='Tipo de Mantenimiento')),
                ('equipo', models.CharField(max_length=150, verbose_name='Equipo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('actividades', models.TextField(verbose_name='Actividades realizadas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Plan de Mantenimiento',
                'verbose_name_plural': 'Planes de Mantenimiento',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
