# Generated by Django 4.2.23 on 2025-09-01 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaBeneficiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Área / Beneficiario')),
            ],
            options={
                'verbose_name': 'Área Beneficiaria',
                'verbose_name_plural': 'Áreas Beneficiarias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Mantenimiento')),
            ],
            options={
                'verbose_name': 'Tipo de Mantenimiento',
                'verbose_name_plural': 'Tipos de Mantenimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='area_beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.areabeneficiaria', verbose_name='Área / Beneficiario'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.equipo', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo_mantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipomantenimiento', verbose_name='Tipo de Mantenimiento'),
        ),
    ]
